spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://:3306/
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#融宝相关配置
reapal:
  version: 1.0
  pay-url: http://api.reapal.com
  topay-url: https://agentpay.reapal.com/agentpay
  merchantId: 
  appKey: 
  seller_email: 
  pubKeyUrl: /data/cert/rongbao.cer
  privateKey: /data/cert/100000001301356.pfx
  privateKeyPwd: 
notify:
  url: 
jww:
  url: 
