spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.240:3306/cqck_db
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#融宝相关配置
reapal:
  version: 1.0
  pay-url: http://testapi.reapal.com
  topay-url: http://testagentpay.reapal.com/agentpay/agentpay
  merchantId: 
  appKey: 
  seller_email: 850138237@qq.com
  pubKeyUrl: /data/cert/rongbao_test.cer
  privateKey: /data/cert/rongbao_test.pfx
  privateKeyPwd: 
notify:
  url: 
jww:
  url: 



