spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://cqck2017.mysql.rds.aliyuncs.com:3306/cqshop_db
    username: cqshop_web
    password: Jinvovo2015
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#融宝相关配置
reapal:
  version: 1.0
  pay-url: http://api.reapal.com
  topay-url: http://agentpay.reapal.com/agentpay
  merchantId: 100000001301356
  appKey: 2a8e9cab468abe859f8c1adfd1b63a2dcdcd05b3152a50g0a37e323b97df7835
  seller_email: 893448785@qq.com
  pubKeyUrl: /data/cert/rongbao.cer
  privateKey: /data/cert/100000001301356.pfx
  privateKeyPwd: jinvv6
notify:
  url: http://118.178.151.253:88
jww:
  url: http://t.jinvovo.com:8988